apiVersion: batch/v1
kind: Job
metadata:
  name: first-incident
  namespace: observability-lab
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: first-incident
    spec:
      restartPolicy: Never
      containers:
        - name: traffic
          image: observability-lab-app:0.1.0
          imagePullPolicy: Never
          command: ["python", "traffic.py"]
          env:
            - name: TARGET
              value: http://checkout:8080/checkout
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 256Mi
